src/Entity/WpUser.php
<?php

namespace App\Entity;

use App\Repository\WpUserRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WpUserRepository::class)
 * @ORM\Table(name="wp_users")
 */
class WpUser
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_nicename;

    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_login;

    private $first_name;
    private $last_name;
    
    private $user_resumes_count;
    
    private $user_resumes_last_updated;
    
    
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $user_registered;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $display_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserNicename(): ?string
    {
        return $this->user_nicename;
    }

    public function setUserNicename(?string $user_nicename): self
    {
        $this->user_nicename = $user_nicename;

        return $this;
    }

    public function getUserEmail(): ?string
    {
        return $this->user_email;
    }

    public function setUserEmail(string $user_email): self
    {
        $this->user_email = $user_email;

        return $this;
    }

    public function getUserRegistered(): ?\DateTimeInterface
    {
        return $this->user_registered;
    }

    public function setUserRegistered(\DateTimeInterface $user_registered): self
    {
        $this->user_registered = $user_registered;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }
    
    
    
    public function getUser_nicename() {
        return $this->user_nicename;
    }

    public function getUser_login() {
        return $this->user_login;
    }

    public function getUser_resumes_count() {
        return $this->user_resumes_count;
    }

    public function getUser_resumes_last_updated() {
        return $this->user_resumes_last_updated;
    }

    public function getUser_email() {
        return $this->user_email;
    }

    public function getUser_registered() {
        return $this->user_registered;
    }

    public function getDisplay_name() {
        return $this->display_name;
    }

    public function setUser_nicename($user_nicename): void {
        $this->user_nicename = $user_nicename;
    }

    public function setUser_login($user_login): void {
        $this->user_login = $user_login;
    }

    public function setUser_resumes_count($user_resumes_count): void {
        $this->user_resumes_count = $user_resumes_count;
    }

    public function setUser_resumes_last_updated($user_resumes_last_updated): void {
        $this->user_resumes_last_updated = $user_resumes_last_updated;
    }

    public function setUser_email($user_email): void {
        $this->user_email = $user_email;
    }

    public function setUser_registered($user_registered): void {
        $this->user_registered = $user_registered;
    }

    public function setDisplay_name($display_name): void {
        $this->display_name = $display_name;
    }


    
    public function getFirst_name() {
        return $this->first_name;
    }

    public function getLast_name() {
        return $this->last_name;
    }

    public function setFirst_name($first_name): void {
        $this->first_name = $first_name;
    }

    public function setLast_name($last_name): void {
        $this->last_name = $last_name;
    }


    
    
}

src/Form/WpUserType.php
<?php

namespace App\Form;

use App\Entity\WpUser;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WpUserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('user_nicename')
            ->add('user_email')
            ->add('user_registered')
            ->add('display_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => WpUser::class,
        ]);
    }
}

src/Controller/WpUserController.php
<?php

namespace App\Controller;

use App\Entity\WpUser;
use App\Form\WpUserType;
use App\Repository\WpUserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

/**
 * @Route("/wp/user")
 */
class WpUserController extends AbstractController {

    private $em;

    public function __construct(\Doctrine\ORM\EntityManagerInterface $em) {
        $this->em = $em;
    }

    /**
     * @Route("/dashboard", name="app_wp_user_dashboard", methods={"GET|POST"})
     */
    public function dashboard(\Doctrine\ORM\EntityManagerInterface $em, Request $request) {

        $wpDashboardSearch = new \App\Entity\WpUserSearch();

        $searchForm = $this->createForm('App\Form\WpDashboardSearchType', $wpDashboardSearch);
        $searchForm->handleRequest($request);

        $curriculosToday = 0;
        $curriculos7Days = 0;
        $curriculos30Days = 0;
        $curriculosByLocationFilter = [];

        $vagasToday = 0;
        $vagas7Days = 0;
        $vagas30Days = 0;
        $vagasByRegionFilter = [];

        $candidaturasToday = 0;
        $candidaturas7Days = 0;
        $candidaturas30Days = 0;
        $candidaturasByRegionFilter = [];

        $candidatosFilter = 0;
        $curriculosFilter = 0;
        $vagasFilter = 0;
        $candidaturasFilter = 0;

        $intervalInDays = 1;

        if ($searchForm->isSubmitted() && $searchForm->isValid()) {

            $dataInicio = $searchForm["data_inicio"]->getData();
            $dataFim = $searchForm["data_fim"]->getData();
            $location = $searchForm["location"]->getData();

            if ($dataInicio == NULL):
                $datetime = new \DateTime();
                $dataInicio = $datetime->modify("-6 year");
            endif;

            if ($dataFim == NULL):
                $datetime = new \DateTime();
                $dataFim = $datetime->modify("1 day");
            endif;

            $candidatosFilter = $this->countCandidatos($dataInicio, $dataFim);
            $curriculosFilter = $this->countCurriculos($dataInicio, $dataFim, $location);
            $vagasFilter = $this->countVagas($dataInicio, $dataFim, $location);
            $candidaturasFilter = $this->countCandidaturas($dataInicio, $dataFim, $location);

            //$candidatosByLocationFilter = $this->countCandidatos($dataInicio, $dataFim);
            $curriculosByLocationFilter = $this->countCurriculosByLocation($dataInicio, $dataFim);
            $vagasByRegionFilter = $this->countVagasByRegion($dataInicio, $dataFim);
            $candidaturasByRegionFilter = $this->countCandidaturasByRegion($dataInicio, $dataFim);

            $interval = $dataInicio->diff($dataFim);
            $intervalInDays = $interval->days + 1;

            // HOJE

            $today = new \DateTime();
            $datetime = new \DateTime();
            //dump('today = '.$today);

            $last7Days = clone $datetime->modify("-6 day");
            $last30Days = clone $datetime->modify("-22 day");

            $candidatosToday = $this->countCandidatos($today, $today);
            $candidatos7Days = $this->countCandidatos($last7Days, $today);
            $candidatos30Days = $this->countCandidatos($last30Days, $today);

            $curriculosToday = $this->countCurriculos($today, $today, $location);
            $curriculos7Days = $this->countCurriculos($last7Days, $today, $location);
            $curriculos30Days = $this->countCurriculos($last30Days, $today, $location);

            $vagasToday = $this->countVagas($today, $today, $location);
            $vagas7Days = $this->countVagas($last7Days, $today, $location);
            $vagas30Days = $this->countVagas($last30Days, $today, $location);

            $candidaturasToday = $this->countCandidaturas($today, $today, $location);
            $candidaturas7Days = $this->countCandidaturas($last7Days, $today, $location);
            $candidaturas30Days = $this->countCandidaturas($last30Days, $today, $location);
        } else {


            // HOJE

            $today = new \DateTime();
            $datetime = new \DateTime();
            //dump('today = '.$today);

            $last7Days = clone $datetime->modify("-6 day");
            $last30Days = clone $datetime->modify("-22 day");

            $candidatosToday = $this->countCandidatos($today, $today);
            $candidatos7Days = $this->countCandidatos($last7Days, $today);
            $candidatos30Days = $this->countCandidatos($last30Days, $today);

            $curriculosToday = $this->countCurriculos($today, $today, null);
            $curriculos7Days = $this->countCurriculos($last7Days, $today, null);
            $curriculos30Days = $this->countCurriculos($last30Days, $today, null);

            $vagasToday = $this->countVagas($today, $today, null);
            $vagas7Days = $this->countVagas($last7Days, $today, null);
            $vagas30Days = $this->countVagas($last30Days, $today, null);

            $candidaturasToday = $this->countCandidaturas($today, $today, null);
            $candidaturas7Days = $this->countCandidaturas($last7Days, $today, null);
            $candidaturas30Days = $this->countCandidaturas($last30Days, $today, null);
        }



        $results = ['candidatosToday' => $candidatosToday,
            'candidatos7Days' => $candidatos7Days,
            'candidatos30Days' => $candidatos30Days,
            'candidatosFilter' => $candidatosFilter,
            'curriculosToday' => $curriculosToday,
            'curriculos7Days' => $curriculos7Days,
            'curriculos30Days' => $curriculos30Days,
            'curriculosFilter' => $curriculosFilter,
            'curriculosByLocationFilter' => $curriculosByLocationFilter,
            'vagasToday' => $vagasToday,
            'vagas7Days' => $vagas7Days,
            'vagas30Days' => $vagas30Days,
            'vagasFilter' => $vagasFilter,
            'vagasByRegionFilter' => $vagasByRegionFilter,
            'candidaturasToday' => $candidaturasToday,
            'candidaturas7Days' => $candidaturas7Days,
            'candidaturas30Days' => $candidaturas30Days,
            'candidaturasFilter' => $candidaturasFilter,
            'candidaturasByRegionFilter' => $candidaturasByRegionFilter,
            'intervalInDays' => $intervalInDays
        ];

        // parameters to template
        return $this->render('wp_user/dashboard.html.twig', ['search_form' => $searchForm->createView(), 'results' => $results
        ]);
    }

    public function countCandidatos($dataInicio, $dataFim, $calculationMethod = 'count') {

        $query = "SELECT " . $calculationMethod . "(wp_users.id) as candidatos FROM wp_users join wp_usermeta on wp_users.id = wp_usermeta.user_id  "
                . "where 1=1 AND wp_usermeta.meta_key = 'wp_capabilities' and wp_usermeta.meta_value like '%candidate%' ";

        if (!empty($dataInicio)) {
            $query = $query . " AND wp_users.user_registered >= '" . $dataInicio->format("Y-m-d") . " 00:00'";
        }

        if (!empty($dataFim)) {
            $query = $query . " AND wp_users.user_registered < '" . $dataFim->format("Y-m-d") . " 23:59'";
        }


        if ($calculationMethod == "avg"):

        endif;

        $stmt = $this->em->getConnection()->prepare($query);
        $resultSet = $stmt->executeQuery();
        $candidatos = $resultSet->fetchAllAssociative();
        return $candidatos[0]['candidatos'];
    }

    public function countCurriculos($dataInicio, $dataFim, $location) {

        $query = "SELECT count(p.id) as curriculos FROM wp_posts p join wp_postmeta pm on p.id = pm.post_id "
                . "where post_type = 'resume' and post_status = 'publish' and pm.meta_key = '_candidate_location'";

        if (!empty($dataInicio)) {
            $query = $query . " AND p.post_date >= '" . $dataInicio->format("Y-m-d") . " 00:00'";
        }

        if (!empty($dataFim)) {
            $query = $query . " AND p.post_date < '" . $dataFim->format("Y-m-d") . " 23:59'";
        }

        if (!empty($location)) {
            $query = $query . "and pm.meta_key = '_candidate_location' and pm.meta_value = '" . $location."'";
        }


        
        $stmt = $this->em->getConnection()->prepare($query);
        $resultSet = $stmt->executeQuery();
        $candidatos = $resultSet->fetchAllAssociative();
        return $candidatos[0]['curriculos'];
    }

    public function countCurriculosByLocation($dataInicio, $dataFim) {

        $query = "SELECT count(p.id) as curriculos, pm.meta_value as location FROM wp_posts p join wp_postmeta pm on p.id = pm.post_id "
                . "where post_type = 'resume' and post_status = 'publish' and pm.meta_key = '_candidate_location'";

        if (!empty($dataInicio)) {
            $query = $query . " AND p.post_date >= '" . $dataInicio->format("Y-m-d") . " 00:00'";
        }

        if (!empty($dataFim)) {
            $query = $query . " AND p.post_date < '" . $dataFim->format("Y-m-d") . " 23:59'";
        }

        $query = $query . " GROUP by location ORDER BY curriculos DESC ";
        
    

        $stmt = $this->em->getConnection()->prepare($query);
        $resultSet = $stmt->executeQuery();
        $curriculos = $resultSet->fetchAllAssociative();
        return $curriculos;
    }

    public function countVagas($dataInicio, $dataFim, $location) {

       // $query = "SELECT count(p.id) as vagas FROM wp_posts p where post_type = 'job_listing' and post_status = 'publish' ";
        
        
                $query = "SELECT count(p.id) as vagas
                FROM wp_posts p  
                join wp_term_relationships on p.id = wp_term_relationships.object_id
                join wp_term_taxonomy on wp_term_relationships.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id 

templates/wp_user/_delete_form.html.twig
<form method="post" action="{{ path('app_wp_user_delete', {'id': wp_user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ wp_user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/wp_user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/wp_user/dashboard.html.twig
{% extends 'base.html.twig' %}

{% form_theme search_form 'bootstrap_5_layout.html.twig' %}

{% block title %}Dashboard{% endblock %}


{% block stylesheets %}
    {{ parent() }}

    <style>
        .table-wrapper {
            width: 100%;
            max-height: 400px;
            overflow: auto;
            display:inline-block;
        }
    </style>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
{% endblock %}


{% block body %}


    <div class="container  bg-light">
        <h3>Filtro de Pesquisa de Resultados</h3>
        {{ form_start(search_form)}}

        <form class="row g-3 ">
            <div class="row g-3">
                <div class="col-sm-3">
                    {#<input type="text" class="form-control" placeholder="Data de Inicio" aria-label="Data de Inicio">#}
                    {{ form_row(search_form.data_inicio) }}
                </div>
                <div class="col-sm-3">
                    {#<input type="text" class="form-control" placeholder="Data de Fim" aria-label="Data de Inicio">#}
                    {{ form_row(search_form.data_fim) }}
                </div>
                

                <div class="col-sm-3">
                    <input type="submit" class="btn btn-primary" value="Filtrar">
                    <input type="button" class="btn btn-secondary" value="Limpar" onclick="clearForm();">
                </div>
            </div>
            {{ form_rest(search_form) }}
            {{ form_end(search_form) }}
            <br>

            </div> 




            <div class="container">
                <hr/>


                <div class="row">
                    <div class="col">

                        <h2>CANDIDATOS</h2>
                        <table class="table  table-striped">
                            <thead>         
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">MÉDIA</th>
                                    <th scope="col">TOTAL</th>
                                </tr>
                            </thead>          

                            <tbody>
                                <tr>
                                    <td>Hoje</td>
                                    <td>{{ results['candidatosToday'] }}</td>
                                    <td>{{ results['candidatosToday'] }}</td>
                                </tr>


                                <tr>
                                    <td>Últimos 7 dias</td>
                                    <td>{{ (results['candidatos7Days'] / 7)|round(0, 'ceil') }}</td>
                                    <td>{{ results['candidatos7Days'] }}</td>
                                </tr>

                                <tr>
                                    <td>Últimos 30 dias</td>
                                    <td>{{ (results['candidatos30Days'] /30) |round(0, 'ceil')}}</td>
                                    <td>{{ results['candidatos30Days'] }}</td>
                                </tr>

                                <tr>
                                    <td>Resultado do filtro</td>
                                    <td>{{ (results['candidatosFilter'] /  results['intervalInDays']) |round(0, 'ceil')}}</td>
                                    <td>{{ results['candidatosFilter'] }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>


                    <div class="col">
                        <h2>CURRICULOS</h2>
                        <table class="table  table-striped">
                            <thead>         
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">MÉDIA</th>
                                    <th scope="col">TOTAL</th>
                                </tr>
                            </thead>          

                            <tbody>
                                <tr>
                                    <td>Hoje</td>
                                    <td>{{ results['curriculosToday'] }}</td>
                                    <td>{{ results['curriculosToday'] }}</td>
                                </tr>


                                <tr>
                                    <td>Últimos 7 dias</td>
                                    <td>{{ (results['curriculos7Days'] / 7 ) |round(0, 'ceil')}}</td>
                                    <td>{{ results['curriculos7Days'] }}</td>
                                </tr>

                                <tr>
                                    <td>Últimos 30 dias</td>
                                    <td>{{ (results['curriculos30Days'] /30) |round(0, 'ceil') }}</td>
                                    <td>{{ results['curriculos30Days'] }}</td>
                                </tr>

                                <tr>
                                    <td>Resultado do filtro</td>
                                    <td>{{ (results['curriculosFilter'] /  results['intervalInDays']) |round(0, 'ceil') }}</td>
                                    <td>{{ results['curriculosFilter'] }}</td>
                                </tr>
                            </tbody>
                        </table>



                        <div class="table-wrapper">
                            <table class="table table-sm">

                                <tr>
                                    <td colspan="3"><b>Por Região</b></td>
                                </tr>


                                {% for curriculo in results['curriculosByLocationFilter'] %}
                                    <tr>
                                        <td></td>
                                        <td>{{ curriculo.location }}</td>
                                        <td>{{ curriculo.curriculos }}</td>

                                    </tr>

                                {% endfor %}


                            </table>
                        </div>
                    </div>
                </div>


                <!-- start second row -->
                <div class="row">
                    <div class="col">
                        <br>
                        <h2>VAGAS</h2>
                        <table class="table  table-striped">
                            <thead>         
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">MÉDIA</th>
                                    <th scope="col">TOTAL</th>
                                </tr>
                            </thead>          

                            <tbody>
                                <tr>
                                    <td>Hoje</td>
                                    <td>{{ results['vagasToday'] }}</td>
                                    <td>{{ results['vagasToday'] }}</td>
                                </tr>


                                <tr>
                                    <td>Últimos 7 dias</td>
                                    <td>{{ (results['vagas7Days'] / 7) |round(0, 'ceil') }}</td>
                                    <td>{{ results['vagas7Days'] }}</td>
                                </tr>

                                <tr>
                                    <td>Últimos 30 dias</td>
                                    <td>{{ (results['vagas30Days'] /30) |round(0, 'ceil') }}</td>
                                    <td>{{ results['vagas30Days'] }}</td>
                                </tr>

                                <tr>
                                    <td>Resultado do filtro</td>
                                    <td>{{ (results['vagasFilter'] /  results['intervalInDays']) |round(0, 'ceil') }}</td>
                                    <td>{{ results['vagasFilter'] }}</td>
                                </tr>



                            </tbody>
                        </table>



                        <div class="table-wrapper">
                            <table class="table table-sm">
                                <tr>
                                    <td colspan="3"><b>Por Região</b></td>
                                </tr>
                                {% for vaga in results['vagasByRegionFilter'] %}
                                    <tr>
                                        <td></td>
                                        <td>{{ vaga.region }}</td>
                                        <td>{{ vaga.vagas }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>

                    </div>


                    <div class="col">
                        <br>
                        <h2>CANDIDATURAS</h2>
                        <table class="table  table-striped">
                            <thead>         
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">MÉDIA</th>
                                    <th scope="col">TOTAL</th>
                                </tr>
                            </thead>          

                            <tbody>
                                <tr>
                                    <td>Hoje</td>
                                    <td>{{ results['candidaturasToday'] }}</td>
                                    <td>{{ results['candidaturasToday'] }}</td>
                                </tr>


                                <tr>
                                    <td>Últimos 7 dias</td>
                                    <td>{{ (results['candidaturas7Days'] / 7) |round(0, 'ceil') }}</td>
                                    <td>{{ results['candidaturas7Days'] }}</td>
                                </tr>

                                <tr>
                                    <td>Últimos 30 dias</td>
                                    <td>{{ (results['candidaturas30Days'] /30 ) |round(0, 'ceil')}}</td>
                                    <td>{{ results['candidaturas30Days'] }}</td>
                                </tr>

                                <tr>
                                    <td>Resultado do filtro</td>
                                    <td>{{ (results['candidaturasFilter'] /  results['intervalInDays']) |round(0, 'ceil') }}</td>
                                    <td>{{ results['candidaturasFilter'] }}</td>
                                </tr>
                            </tbody>
                        </table>

                                <div class="table-wrapper">
                            <table class="table table-sm">
                                <tr>
                                    <td colspan="3"><b>Por Região</b></td>
                                </tr>
                                {% for candidatura in results['candidaturasByRegionFilter'] %}
                                    <tr>
                                        <td></td>
                                        <td>{{ candidatura.region }}</td>
                                        <td>{{ candidatura.candidaturas }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>


                    </div>
                </div>
                <!-- end second row -->





            </div>



            <script type="text/javascript">



                function clearForm() {
                    var elements = document.getElementsByTagName('select');
                    for (var i = 0; i < elements.length; i++)
                    {
                        elements[i].selectedIndex = 0;
                    }


                }
            </script>


        {% endblock %}

templates/wp_user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit WpUser{% endblock %}

{% block body %}
    <h1>Edit WpUser</h1>

    {{ include('wp_user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_wp_user_index') }}">back to list</a>

    {{ include('wp_user/_delete_form.html.twig') }}
{% endblock %}

templates/wp_user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New WpUser{% endblock %}

{% block body %}
    <h1>Create new WpUser</h1>

    {{ include('wp_user/_form.html.twig') }}

    <a href="{{ path('app_wp_user_index') }}">back to list</a>
{% endblock %}

templates/wp_user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}WpUser{% endblock %}

{% block body %}
    <h1>WpUser</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ wp_user.id }}</td>
            </tr>
            <tr>
                <th>User_nicename</th>
                <td>{{ wp_user.userNicename }}</td>
            </tr>
            <tr>
                <th>User_email</th>
                <td>{{ wp_user.userEmail }}</td>
            </tr>
            <tr>
                <th>User_registered</th>
                <td>{{ wp_user.userRegistered ? wp_user.userRegistered|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Display_name</th>
                <td>{{ wp_user.displayName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_wp_user_index') }}">back to list</a>

    <a href="{{ path('app_wp_user_edit', {'id': wp_user.id}) }}">edit</a>

    {{ include('wp_user/_delete_form.html.twig') }}
{% endblock %}